/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlannerSingleRouteImport } from './routes/planner.single'
import { Route as PlannerDetailedRouteImport } from './routes/planner.detailed'
import { Route as ApiTalkRouteImport } from './routes/api/talk'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerSingleRoute = PlannerSingleRouteImport.update({
  id: '/planner/single',
  path: '/planner/single',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerDetailedRoute = PlannerDetailedRouteImport.update({
  id: '/planner/detailed',
  path: '/planner/detailed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTalkRoute = ApiTalkRouteImport.update({
  id: '/api/talk',
  path: '/api/talk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/talk': typeof TalkRoute
  '/tools': typeof ToolsRoute
  '/api/talk': typeof ApiTalkRoute
  '/planner/detailed': typeof PlannerDetailedRoute
  '/planner/single': typeof PlannerSingleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/talk': typeof TalkRoute
  '/tools': typeof ToolsRoute
  '/api/talk': typeof ApiTalkRoute
  '/planner/detailed': typeof PlannerDetailedRoute
  '/planner/single': typeof PlannerSingleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/talk': typeof TalkRoute
  '/tools': typeof ToolsRoute
  '/api/talk': typeof ApiTalkRoute
  '/planner/detailed': typeof PlannerDetailedRoute
  '/planner/single': typeof PlannerSingleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/plans'
    | '/register'
    | '/talk'
    | '/tools'
    | '/api/talk'
    | '/planner/detailed'
    | '/planner/single'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/plans'
    | '/register'
    | '/talk'
    | '/tools'
    | '/api/talk'
    | '/planner/detailed'
    | '/planner/single'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/plans'
    | '/register'
    | '/talk'
    | '/tools'
    | '/api/talk'
    | '/planner/detailed'
    | '/planner/single'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  TalkRoute: typeof TalkRoute
  ToolsRoute: typeof ToolsRoute
  ApiTalkRoute: typeof ApiTalkRoute
  PlannerDetailedRoute: typeof PlannerDetailedRoute
  PlannerSingleRoute: typeof PlannerSingleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/single': {
      id: '/planner/single'
      path: '/planner/single'
      fullPath: '/planner/single'
      preLoaderRoute: typeof PlannerSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/detailed': {
      id: '/planner/detailed'
      path: '/planner/detailed'
      fullPath: '/planner/detailed'
      preLoaderRoute: typeof PlannerDetailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/talk': {
      id: '/api/talk'
      path: '/api/talk'
      fullPath: '/api/talk'
      preLoaderRoute: typeof ApiTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  TalkRoute: TalkRoute,
  ToolsRoute: ToolsRoute,
  ApiTalkRoute: ApiTalkRoute,
  PlannerDetailedRoute: PlannerDetailedRoute,
  PlannerSingleRoute: PlannerSingleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
